/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CreateUserReq,
 *   !proto.User>}
 */
const methodDescriptor_ChatService_createUser = new grpc.web.MethodDescriptor(
  '/ChatService/createUser',
  grpc.web.MethodType.UNARY,
  proto.CreateUserReq,
  proto.User,
  /**
   * @param {!proto.CreateUserReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.User.deserializeBinary
);


/**
 * @param {!proto.CreateUserReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatService/createUser',
      request,
      metadata || {},
      methodDescriptor_ChatService_createUser,
      callback);
};


/**
 * @param {!proto.CreateUserReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.User>}
 *     Promise that resolves to the response
 */
proto.ChatServicePromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatService/createUser',
      request,
      metadata || {},
      methodDescriptor_ChatService_createUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserReq,
 *   !proto.ChatList>}
 */
const methodDescriptor_ChatService_getAllChats = new grpc.web.MethodDescriptor(
  '/ChatService/getAllChats',
  grpc.web.MethodType.UNARY,
  proto.UserReq,
  proto.ChatList,
  /**
   * @param {!proto.UserReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ChatList.deserializeBinary
);


/**
 * @param {!proto.UserReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ChatList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ChatList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.getAllChats =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatService/getAllChats',
      request,
      metadata || {},
      methodDescriptor_ChatService_getAllChats,
      callback);
};


/**
 * @param {!proto.UserReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ChatList>}
 *     Promise that resolves to the response
 */
proto.ChatServicePromiseClient.prototype.getAllChats =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatService/getAllChats',
      request,
      metadata || {},
      methodDescriptor_ChatService_getAllChats);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.MessageHistoryReq,
 *   !proto.MessagesList>}
 */
const methodDescriptor_ChatService_getMessagesHistory = new grpc.web.MethodDescriptor(
  '/ChatService/getMessagesHistory',
  grpc.web.MethodType.UNARY,
  proto.MessageHistoryReq,
  proto.MessagesList,
  /**
   * @param {!proto.MessageHistoryReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.MessagesList.deserializeBinary
);


/**
 * @param {!proto.MessageHistoryReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.MessagesList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.MessagesList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.getMessagesHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatService/getMessagesHistory',
      request,
      metadata || {},
      methodDescriptor_ChatService_getMessagesHistory,
      callback);
};


/**
 * @param {!proto.MessageHistoryReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.MessagesList>}
 *     Promise that resolves to the response
 */
proto.ChatServicePromiseClient.prototype.getMessagesHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatService/getMessagesHistory',
      request,
      metadata || {},
      methodDescriptor_ChatService_getMessagesHistory);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ChatMessage,
 *   !proto.Empty>}
 */
const methodDescriptor_ChatService_sendMessage = new grpc.web.MethodDescriptor(
  '/ChatService/sendMessage',
  grpc.web.MethodType.UNARY,
  proto.ChatMessage,
  proto.Empty,
  /**
   * @param {!proto.ChatMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Empty.deserializeBinary
);


/**
 * @param {!proto.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.sendMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatService/sendMessage',
      request,
      metadata || {},
      methodDescriptor_ChatService_sendMessage,
      callback);
};


/**
 * @param {!proto.ChatMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Empty>}
 *     Promise that resolves to the response
 */
proto.ChatServicePromiseClient.prototype.sendMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatService/sendMessage',
      request,
      metadata || {},
      methodDescriptor_ChatService_sendMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserReq,
 *   !proto.ChatMessage>}
 */
const methodDescriptor_ChatService_receiveMessages = new grpc.web.MethodDescriptor(
  '/ChatService/receiveMessages',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.UserReq,
  proto.ChatMessage,
  /**
   * @param {!proto.UserReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ChatMessage.deserializeBinary
);


/**
 * @param {!proto.UserReq} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.ChatServiceClient.prototype.receiveMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/receiveMessages',
      request,
      metadata || {},
      methodDescriptor_ChatService_receiveMessages);
};


/**
 * @param {!proto.UserReq} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ChatMessage>}
 *     The XHR Node Readable Stream
 */
proto.ChatServicePromiseClient.prototype.receiveMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatService/receiveMessages',
      request,
      metadata || {},
      methodDescriptor_ChatService_receiveMessages);
};


module.exports = proto;

